// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANmSblV8YdSZTS9WvqTAixFu04Q4HMh5g',
    appId: '1:725566773970:web:5844461a3c6ee1d565eb0b',
    messagingSenderId: '725566773970',
    projectId: 'gimenez-firebase-demo-45a6e',
    authDomain: 'gimenez-firebase-demo-45a6e.firebaseapp.com',
    storageBucket: 'gimenez-firebase-demo-45a6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcJ6tjsE9i8nX1jDCIYY4sbZGSkyG94kI',
    appId: '1:725566773970:android:5ce223167d88a89365eb0b',
    messagingSenderId: '725566773970',
    projectId: 'gimenez-firebase-demo-45a6e',
    storageBucket: 'gimenez-firebase-demo-45a6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdztNde1rs8XiM8ylEQEYFWL61SFh0r_8',
    appId: '1:725566773970:ios:55d8d0dca1a38b4765eb0b',
    messagingSenderId: '725566773970',
    projectId: 'gimenez-firebase-demo-45a6e',
    storageBucket: 'gimenez-firebase-demo-45a6e.appspot.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );

}