// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDcXCEDyBOvinHgbjLZp5qLwsyQ1bG4dM',
    appId: '1:1061055579558:web:98e784e68ee6bf58eefb67',
    messagingSenderId: '1061055579558',
    projectId: 'gimenez-firebase-demo',
    authDomain: 'gimenez-firebase-demo.firebaseapp.com',
    storageBucket: 'gimenez-firebase-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC61Wdas2iTiLQKUMia27GMCBlaBDI9tyY',
    appId: '1:1061055579558:android:87ad05fa213a15aeeefb67',
    messagingSenderId: '1061055579558',
    projectId: 'gimenez-firebase-demo',
    storageBucket: 'gimenez-firebase-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM_So-f1zqoJ2YJAMC-XSKyJAWReaE0WU',
    appId: '1:1061055579558:ios:dd63d8f14ad802f8eefb67',
    messagingSenderId: '1061055579558',
    projectId: 'gimenez-firebase-demo',
    storageBucket: 'gimenez-firebase-demo.appspot.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );
}
